name: Spring Boot CI/CD

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Copy JAR file
      run: cp target/*.jar .

    - name: Build Docker image
      run: docker build -t palmerovicdev/fsa-storage-service .

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: docker push palmerovicdev/fsa-storage-service

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull palmerovicdev/fsa-storage-service
          docker stop fsa-storage-service || true
          docker rm fsa-storage-service || true
          docker run -d -p 8080:8080 --name fsa-storage-service palmerovicdev/fsa-storage-service
