name: Spring Boot CI/CD

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install
      env:
        DATABASE_URL: ${{vars.DATABASE_URL}}
        DATABASE_USER: ${{vars.DATABASE_USER}}
        DATABASE_PASS: ${{vars.DATABASE_PASS}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/your-repo-name:tagname

    - name: Run Deployment Trigger
      run: |
        curl -X GET ${{secrets.DEPLOY_URL}}