name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Copy JAR file
      run: cp target/*.jar .

    - name: Build Docker image
      run: docker build -t palmerovicdev/fsa-storage-service .

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: docker push palmerovicdev/fsa-storage-service

    - name: Run Deployment Trigger
      run: |
        curl -X GET http://217.15.171.136:3000/api/deploy/d6ba72fdbbd7fb9ef5a2a7002f3081d33c8aeb46d6ca7305

