name: Spring Boot CI/CD

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install
      env:
        DATABASE_URL: ${{vars.DATABASE_URL}}
        DATABASE_USER: ${{vars.DATABASE_USER}}
        DATABASE_PASS: ${{vars.DATABASE_PASS}}

    - name: Copy artifact to root
      run: cp target/fsa-storage-service-1.0.0.jar .
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        tags: palmerovicdev/fsa-storage-service:latest
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PASS=${{ secrets.DATABASE_PASS }}
          SERVER_BASE_URL=${{ secrets.SERVER_BASE_URL }}

    - name: Run Deployment Trigger
      run: |
        curl -X GET ${{secrets.DEPLOY_URL}}